@startuml Deployment Diagram

title Order Processing System - Microservice Architecture

node "User Device" {
  [Web Browser]
}

node "API Gateway" {
}

node "E-commerce System" {
    [Order Service]
    [Product Catelog Service]
    [User Service]
    [Payment Service]
    [Inventory Service]
}

node "Database Server" {
    database "Inventory Database" {
        [Inventory]
    }
    database "User Database" {
        [Users]
    }
    database "Product Database" {
        [Products]
    }
    database "Order Database" {
        [Orders]
    }
}

[Web Browser] --> [API Gateway] : Sends request
[API Gateway] --> [Order Service] : Place order
[Order Service] --> [Payment Service] : Process payment

[Order Service] --> [Inventory Service] : Check inventory
[Inventory Service] --> [Inventory Database] : Fetch inventory data

[Order Service] --> [Order Database] : Update order

[API Gateway] --> [Product Catelog Service] : Browser products
[Product Catelog Service] --> [Product Database] : Fetch products

[API Gateway] --> [User Service] : User actions
[User Service] --> [User Database] : Fetch user data

@endyaml
